# Generated by Django 3.1.7 on 2021-02-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(default='adsda', max_length=100),
            preserve_default=False,
        ),
    ]
